{% set name = "sequenceTools" %}
{% set version = "1.2.2" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/stschiff/{{ name }}/archive/v{{ version }}.tar.gz
  md5: 35bafae8813a7510cadf87057bd42df4

build:
  number: 1
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - stack >=1.7.1
    - zlib
    - wget
    - gmp
    - perl 
    - xz
  run:
    - zlib
    - xz
    - gmp
    - samtools



test:
  commands:
    - pileupCaller --version

about:
  home: https://github.com/stschiff/sequenceTools
  license: MIT
  license_file: LICENSE
  summary: Tools for population genetics on sequencing datas
