{% set version = "3.0.4" %}

package:
  name: glimmerhmm
  version: {{ version }}

source:
  md5: af3626a5eceb2893ba4e19373dfad1b0
  url: https://ccb.jhu.edu/software/glimmerhmm/dl/GlimmerHMM-{{ version }}.tar.gz

build:
  number: 4

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
  run:
    - perl

test:
  commands:
    - glimmerhmm -h > /dev/null

about:
  home: https://ccb.jhu.edu/software/glimmerhmm/
  license: Artistic License
  license_file: LICENSE
  summary: "GlimmerHMM is a gene finder based on a Generalized Hidden Markov Model (GHMM)"
