{% set version = "1.0.0" %}
# {% set db_version = "2019-09-09" %}
{% set name = "KOfamScan" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:

  url: ftp://ftp.genome.jp/pub/tools/kofamscan/archives/kofamscan-{{ version }}/kofamscan-{{ version }}.tar.gz
  sha256: 8d039abc69cc5671c35da8d41c8b48f742190e0b4002b76989e52afe82e963e5
  # - folder: db
  #   url: ftp://ftp.genome.jp/pub/db/kofam/archives/{{ db_version }}/ko_list.gz
  #   sha256: 5a642fdb442e0012b9de37cc513179161aa3548c5a47d3b0306fa5d07a4b3f85
  # - folder: db
  #   url: ftp://ftp.genome.jp/pub/db/kofam/archives/{{ db_version }}/profiles.tar.gz
  #   sha256: 27e1d4486daaa7b20d21734cd7589a0e11104186cf5ae5b1062785c26423fe91

build:
  number: 0
  noarch: generic

requirements:
  run:
    - ruby >=2.4
    - hmmer >=3.1
    - parallel

test:
  commands:
    - exec_annotation --help

about:
  home: https://www.genome.jp/tools/kofamkoala/
  license: MIT License
  license_file: LICENSE.txt
  summary: KofamKOALA assigns K numbers to the user's sequence data by HMMER/HMMSEARCH against KOfam
  description: |
    KofamKOALA assigns K numbers to the user's sequence data by HMMER/HMMSEARCH against KOfam (a customized HMM database of KEGG Orthologs (KOs)).
    K number assignments with scores above the predefined thresholds for individual KOs are more reliable than other proposed assignments.
    Such high score assignments are highlighted with asterisks '*' in the output.
    The K number assignments facilitate the interpretation of the annotation results by linking the user's sequence data to the KEGG pathways and EC numbers.

extra:
  recipe-maintainers:
    - silask
  identifiers:
    - doi:10.1093/bioinformatics/btz859
