package:
  name: probabilistic2020
  version: "1.2.0"

source:
  url: https://files.pythonhosted.org/packages/30/ff/feae37090012be833521cf374700b1609d102fd3dfa8b5690ee657c9708f/probabilistic2020-1.2.0.tar.gz
  sha256: 12e0f9dc3fc47ed2b6edf2d4c9106c20ab442c6282b1b1d51c0146e61362bd49

build:
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-deps -vv
  entry_points:
    - probabilistic2020 = prob2020.console.probabilistic2020:cli_main
    - mut_annotate = prob2020.console.annotate:cli_main
    - extract_gene_seq = prob2020.console.extract_gene_seq:cli_main
    - simulate_non_silent_ratio = prob2020.console.simulate_non_silent_ratio:cli_main
  number: 0

requirements:
  build:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - pandas >=0.17.0
    - pysam

test:
  imports:
    - prob2020
    - prob2020.console
    - prob2020.cpp
    - prob2020.cython
    - prob2020.python

  commands:
    - probabilistic2020 --help
    - mut_annotate --help
    - extract_gene_seq --help
    - simulate_non_silent_ratio --help

about:
  home: https://github.com/KarchinLab/probabilistic2020
  license: Apache-2-0
  summary: Simulates somatic mutations, and calls statistically significant oncogenes and tumor suppressor genes based on a randomization-based test
  license_family: APACHE
