{% set version = "v0.1" %}
{% set sha256 = "6e9eb0dd85ce0b728fb9595cdadd70f6f3d2326cad3eb73e96bad5c2d5fb11c2" %}
package:
  name: odgi
  version: '{{version}}'

source:
  url: https://github.com/vgteam/odgi/archive/{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    
test:
  commands:
    - odgi test

about:
  home: https://github.com/vgteam/odgi
  license: MIT
  summary: An optimized dynamic genome graph implementation