package:
  name: pronto
  version: "1.1.2"

source:
  url: https://files.pythonhosted.org/packages/63/81/afc522c5acd04826703422806ad94bac42bd69f6c28839a35b8c1b224ac1/pronto-1.1.2.zip
  sha256: e413813c319c708617da7db7d3ddc2d8ad06ed8873931161491563fbfa5070ca
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  number: 0
  entry_points:
    - pronto = pronto:main

requirements:
  host:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - pronto
    - pronto.parser

about:
  home: http://github.com/althonos/pronto
  license: MIT License
  summary: 'Python frontend to ontologies'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
