package:
  name: pronto
  version: "1.1.1"

source:
  url: https://files.pythonhosted.org/packages/5f/65/9574cb9b4fc3e235473176e8e3460eba902b286fbc177d58b2477c0bfbc4/pronto-1.1.1.zip
  sha256: 098570beba4d49927e2240c81133750fa3ac4ddbdbdb7f56774c0c3e41b56023
#  patches:
   # List any patch files here
   # - fix.patch

build:
  noarch: python
  number: 0
  entry_points:
    - pronto = pronto:main

requirements:
  host:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  imports:
    - pronto
    - pronto.parser

about:
  home: http://github.com/althonos/pronto
  license: MIT License
  summary: 'Python frontend to ontologies'
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
