{% set version = "2.10.2" %}
{% set bioconda_version = "2.10.2" %}
{% set ngs_version = "2.10.2" %}

package:
  name: sra-tools
  version: '{{ bioconda_version }}'

source:
  - url: https://github.com/ncbi/sra-tools/archive/{{version}}.tar.gz
    sha256: e8f95d5c68528bbb9ea1a817d3a20115c63a6f8ce28b814fbd78a88bbdcf5524
    folder: sra-tools
  - url: https://github.com/ncbi/ncbi-vdb/archive/{{version}}.tar.gz
    sha256: 597383174700949cd6dc158e0528422a36a40d97c966b3a9327751f4e8224e91
    folder: ncbi-vdb
  - url: https://github.com/ncbi/ngs/archive/{{ngs_version}}.tar.gz
    sha256: 613be73b31474b7e3d616ad3d7fea3a6a598a9b3695309a1b1e0bc4224248447
    folder: ngs

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ncbi-ngs-sdk
    - libxml2
    - hdf5
    - perl
  run:
    - perl
    - ncbi-ngs-sdk
    - libxml2
    - hdf5
    - perl-xml-libxml
    - perl-uri

test:
  commands:
    # "Frequently Used Tools"
    - sratools help
    # Ensure the old executable names still work
    - fastq-dump --help > /dev/null
    - prefetch --help > /dev/null
    - sam-dump --help > /dev/null
    - sra-pileup --help > /dev/null
    - vdb-config --help > /dev/null
    - vdb-decrypt --help > /dev/null
    - fastq-dump -N 1 -X 1 SRR000001 && grep '@SRR000001.1' SRR000001.fastq
    - fasterq-dump --help > /dev/null

about:
  home: https://github.com/ncbi/sra-tools
  license: Public Domain
  summary: SRA Toolkit and SDK from NCBI
  description:  |
    The SRA Toolkit and SDK from NCBI is a collection of tools and libraries
    for using data in the INSDC Sequence Read Archives.

extra:
  notes: 'After installation, you should run the configuration tool: ./vdb-config
    -i. This tool will setup your download/cache area for downloaded files and references.'
